const values={age:45,spouse:1,children:2,childAges:[10,15],education:'public',housing:120000,carCycle:8,carType:'standard',travel:2,dining:4,drinking:1,smoking:0,lessons:2};
const steps=[...document.querySelectorAll('.form-step')];let step=0;
const yenMan=n=>Math.round(n/10000).toLocaleString('ja-JP');

function renderChildAges(){const count=Math.min(values.children,3),wrap=document.querySelector('#childAgeFields');document.querySelector('#childAgesCard').hidden=!count;wrap.innerHTML='';for(let i=0;i<count;i++){if(values.childAges[i]===undefined)values.childAges[i]=i?15:10;const row=document.createElement('div');row.className='child-row';row.innerHTML=`<span>${i+1}人目</span><div class="choices grid-4">${[3,7,10,15,18,22].map((a,j)=>`<button type="button" data-age="${a}" data-index="${i}" class="${values.childAges[i]===a?'selected':''}">${j===0?'未就学':a+'歳'}</button>`).join('')}</div>`;wrap.append(row)}wrap.querySelectorAll('button').forEach(b=>b.onclick=()=>{values.childAges[+b.dataset.index]=+b.dataset.age;renderChildAges()})}
document.querySelectorAll('.choices[data-name]').forEach(group=>group.addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;group.querySelectorAll('button').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');const name=group.dataset.name,raw=btn.dataset.value;values[name]=isNaN(raw)?raw:+raw;if(name==='children')renderChildAges();if(name==='carCycle')document.querySelector('#carTypeCard').hidden=!values.carCycle}));
function showStep(n){step=n;steps.forEach((s,i)=>s.classList.toggle('active',i===n));const pct=(n+1)*25;document.querySelector('#progressBar').style.width=pct+'%';document.querySelector('#progressPercent').textContent=pct+'%';document.querySelector('#progressTitle').textContent=steps[n].dataset.title;document.querySelector('#stepLabel').textContent=`STEP ${n+1} / 4`;document.querySelector('#backBtn').style.visibility=n?'visible':'hidden';document.querySelector('#nextBtn').innerHTML=n===3?'結果を見る <span>→</span>':'次へ進む <span>→</span>';window.scrollTo({top:0,behavior:'smooth'})}
document.querySelector('#nextBtn').onclick=()=>step<3?showStep(step+1):showResults();document.querySelector('#backBtn').onclick=()=>showStep(step-1);

function calculate(){const people=1+values.spouse+values.children;const categories={education:0,housing:values.housing*12*30,car:0,travel:values.travel*people*50000*30,dining:values.dining*7000*12*30,habits:(values.drinking*4000+values.smoking*15000)*12*30,lessons:values.lessons*5000*52*30};const yearly=Array(30).fill(0).map(()=>({education:0,housing:values.housing*12,car:0,travel:values.travel*people*50000,dining:values.dining*7000*12,habits:(values.drinking*4000+values.smoking*15000)*12,lessons:values.lessons*5000*52}));values.childAges.slice(0,values.children).forEach(age=>{for(let y=0;y<30;y++){const a=age+y;let cost=0;if(a>=3&&a<6)cost=values.education==='private'?900000:300000;else if(a<12&&a>=6)cost=values.education==='private'?1600000:350000;else if(a<15&&a>=12)cost=values.education==='private'?1450000:500000;else if(a<18&&a>=15)cost=values.education==='private'?1050000:500000;else if(a<22&&a>=18)cost=values.education==='private'?1500000:1100000;yearly[y].education+=cost;categories.education+=cost}});if(values.carCycle){const price=values.carType==='light'?1800000:3200000;for(let y=values.carCycle-1;y<30;y+=values.carCycle){yearly[y].car+=price;categories.car+=price}}const periods=[];for(let p=0;p<6;p++)periods.push(yearly.slice(p*5,p*5+5).reduce((s,o)=>s+Object.values(o).reduce((a,b)=>a+b,0),0));return{categories,periods,total:Object.values(categories).reduce((a,b)=>a+b,0)}}
const meta={education:['教育費','#5bcfc8'],housing:['住居費','#315d63'],car:['車','#ff9b82'],travel:['旅行','#ffc768'],dining:['外食','#91bfc5'],habits:['嗜好品','#a78bca'],lessons:['習い事','#8fc99a']};
function showResults(){const r=calculate();document.querySelector('#formView').hidden=true;document.querySelector('#resultView').hidden=false;document.querySelector('.topbar').style.display='none';document.querySelector('#totalAmount').innerHTML=`${yenMan(r.total)}<span>万円</span>`;document.querySelector('#donutTotal').textContent=yenMan(r.total);const peak=Math.max(...r.periods),pi=r.periods.indexOf(peak);document.querySelector('#peakText').textContent=`${pi*5+1}〜${pi*5+5}年後`;const reasons=Object.entries(r.categories).sort((a,b)=>b[1]-a[1]).slice(0,2).map(([k])=>meta[k][0]);document.querySelector('#peakReason').textContent=`${reasons.join('と')}が大きな割合を占めます`;document.querySelector('#barChart').innerHTML=r.periods.map((v,i)=>`<div class="bar-col"><strong>${yenMan(v)}</strong><div class="bar ${v===peak?'peak':''}" style="height:${Math.max(10,v/peak*170)}px"></div><small>${i*5+1}〜${i*5+5}年</small></div>`).join('');let start=0;const gradients=[],legend=[];Object.entries(r.categories).sort((a,b)=>b[1]-a[1]).forEach(([k,v])=>{const pct=v/r.total*100,end=start+pct;gradients.push(`${meta[k][1]} ${start}% ${end}%`);legend.push(`<div class="legend-row"><i style="background:${meta[k][1]}"></i><span>${meta[k][0]}</span><strong>${yenMan(v)}万円</strong></div>`);start=end});document.querySelector('#donut').style.background=`conic-gradient(${gradients.join(',')})`;document.querySelector('#legend').innerHTML=legend.join('');renderSimulation(r);window.scrollTo(0,0)}
function renderSimulation(r){const options=[['dining','外食を月2回減らす',Math.min(values.dining,2)*7000*12*30],['travel','旅行を年1回減らす',values.travel? (1+values.spouse+values.children)*50000*30:0],['habits','嗜好品を半分にする',r.categories.habits*.5],['car','車の買い替えを1回減らす',values.carCycle?(values.carType==='light'?1800000:3200000):0]];const wrap=document.querySelector('#simOptions');wrap.innerHTML=options.filter(o=>o[2]>0).map(o=>`<label class="sim-row"><input type="checkbox" data-saving="${o[2]}"><span class="toggle"></span><div><b>${o[1]}</b><small>無理なく続けた場合</small></div><strong>−${yenMan(o[2])}万円</strong></label>`).join('');const update=()=>{const saving=[...wrap.querySelectorAll(':checked')].reduce((s,e)=>s+(+e.dataset.saving),0);document.querySelector('#savingAmount').textContent=`${yenMan(saving)}万円`;document.querySelector('#newTotal').textContent=`見直し後の総支出 ${yenMan(r.total-saving)}万円`};wrap.onchange=update;update()}
function edit(){document.querySelector('#formView').hidden=false;document.querySelector('#resultView').hidden=true;document.querySelector('.topbar').style.display='flex';showStep(3)}document.querySelector('#editBtn').onclick=edit;document.querySelector('#restartBtn').onclick=()=>{location.reload()};renderChildAges();showStep(0);
